/**
 * NFT Minting API
 *
 * This module provides endpoints for minting memes as NFTs on Solana.
 *
 * Required Environment Variables:
 * - SOLANA_RPC_URL: Solana RPC endpoint URL
 * - SECRET_KEY: (Optional) Base58 encoded secret key for the minting wallet
 *
 * Example Usage:
 * POST /api/mint-nft
 * {
 *   "imageUrl": "https://example.com/meme.png",
 *   "prompt": "A funny meme generated by AI"
 * }
 */

import { Connection, Keypair, LAMPORTS_PER_SOL } from "@solana/web3.js";
import { Metaplex, keypairIdentity } from "@metaplex-foundation/js";
import bs58 from "bs58";

/**
 * Mint an NFT from a generated meme
 *
 * This function handles the complete NFT minting process:
 * 1. Sets up Solana connection
 * 2. Creates or uses existing keypair
 * 3. Initializes Metaplex SDK
 * 4. Creates NFT metadata
 * 5. Uploads metadata to Arweave
 * 6. Mints the NFT on Solana
 * 7. Returns transaction details
 *
 * @param {Object} req - Express request object
 * @param {Object} req.body - Request body
 * @param {string} req.body.imageUrl - URL of the image to mint as NFT (required)
 * @param {string} req.body.prompt - User input text for the meme (required)
 * @param {Object} res - Express response object
 * @returns {Promise<void>}
 */
export async function mintNFT(req, res) {
  try {
    const { imageUrl, prompt } = req.body;

    // Validate required parameters
    if (!imageUrl || !prompt) {
      return res
        .status(400)
        .json({ error: "Image URL and prompt are required" });
    }

    // Create description from prompt
    const description = `Meme generated from prompt: ${prompt}`;

    // 1. Set up Solana connection, supporting both NEXT_PUBLIC_ and PUBLIC_ prefixes
    const rpcUrl =
      process.env.NEXT_PUBLIC_SOLANA_RPC_URL ||
      process.env.PUBLIC_SOLANA_RPC_URL ||
      "https://api.devnet.solana.com";
    const connection = new Connection(rpcUrl, "confirmed");

    // 2. Create or use existing keypair
    let keypair;
    if (process.env.SECRET_KEY) {
      // Use existing secret key from environment
      const secretKey = bs58.decode(process.env.SECRET_KEY);
      keypair = Keypair.fromSecretKey(secretKey);
    } else {
      // Generate new keypair for testing
      keypair = Keypair.generate();
      console.log(
        "Generated new keypair for testing:",
        keypair.publicKey.toBase58(),
      );

      // Request small amount of SOL for testing keypair
      try {
        const airdropSignature = await connection.requestAirdrop(
          keypair.publicKey,
          LAMPORTS_PER_SOL * 0.1,
        );
        await connection.confirmTransaction(airdropSignature);
        console.log("Airdrop successful");
      } catch (airdropError) {
        console.warn(
          "Airdrop failed (might be on mainnet):",
          airdropError.message,
        );
      }
    }

    // 3. Initialize Metaplex SDK with correct identity setup
    const metaplex = Metaplex.make(connection).use(keypairIdentity(keypair));

    // 4. Create NFT metadata
    const timestamp = Math.floor(Date.now() / 1000);
    const shortPrompt =
      prompt.length > 20 ? prompt.substring(0, 20) + "..." : prompt;
    const metadata = {
      name: `Meme: ${shortPrompt}`,
      description: description,
      image: imageUrl,
      attributes: [
        {
          trait_type: "Meme Type",
          value: "Generated",
        },
        {
          trait_type: "Timestamp",
          value: timestamp.toString(),
        },
        {
          trait_type: "Prompt",
          value: prompt,
        },
      ],
      external_url: "https://stalkgen.xyz",
      seller_fee_basis_points: 500, // 5%
      creators: [
        {
          address: keypair.publicKey.toBase58(),
          verified: true,
          share: 100,
        },
      ],
    };

    // 5. Upload metadata to Arweave
    console.log("Uploading metadata to Arweave...");
    const { uri } = await metaplex.nfts().uploadMetadata(metadata);
    console.log("Metadata uploaded to:", uri);

    // 6. Mint NFT
    console.log("Minting NFT...");
    const { nft, response } = await metaplex.nfts().create({
      uri: uri,
      name: `Meme: ${shortPrompt}`,
      symbol: "MEME",
      sellerFeeBasisPoints: 500, // 5%
      creators: [
        {
          address: keypair.publicKey,
          verified: true,
          share: 100,
        },
      ],
    });

    // 7. Build Solana Explorer links
    const transactionSignature = response.signature;
    const mintAddress = nft.address.toBase58();
    const cluster = rpcUrl.includes("devnet") ? "devnet" : "mainnet";
    const transactionUrl = `https://solscan.io/tx/${transactionSignature}?cluster=${cluster}`;
    const mintUrl = `https://solscan.io/token/${mintAddress}?cluster=${cluster}`;

    console.log("NFT minted successfully!");
    console.log("Mint address:", mintAddress);
    console.log("Transaction URL:", transactionUrl);

    // 8. Return response
    res.json({
      success: true,
      mintAddress: mintAddress,
      transactionUrl: transactionUrl,
      solscanLink: mintUrl,
      transactionSignature: transactionSignature,
    });
  } catch (error) {
    console.error("Error minting NFT:", error);
    res.status(500).json({
      error: "Failed to mint NFT",
      details: error.message,
    });
  }
}
