/**
 * NFT Minting API
 *
 * This module provides endpoints for minting memes as NFTs on Solana.
 *
 * Required Environment Variables:
 * - SOLANA_RPC_URL: Solana RPC endpoint URL
 * - SECRET_KEY: (Optional) Base58 encoded secret key for the minting wallet
 *
 * Example Usage:
 * POST /api/mint-nft
 * {
 *   "imageUrl": "https://example.com/meme.png",
 *   "prompt": "A funny meme generated by AI"
 * }
 */

import { createUmi } from "@metaplex-foundation/umi-bundle-defaults";
import { mplTokenMetadata } from "@metaplex-foundation/mpl-token-metadata";
import { irysUploader } from "@metaplex-foundation/umi-uploader-irys";
import {
  generateSigner,
  percentAmount,
  signerIdentity,
  sol,
} from "@metaplex-foundation/umi";
import { createGenericFile } from "@metaplex-foundation/umi";
import { createNft } from "@metaplex-foundation/mpl-token-metadata";
import bs58 from "bs58";

/**
 * Mint an NFT from a generated meme
 *
 * This function handles the complete NFT minting process:
 * 1. Sets up Solana connection with Umi
 * 2. Creates or uses existing keypair
 * 3. Uploads metadata to Arweave using Irys
 * 4. Mints the NFT on Solana using mpl-token-metadata
 * 5. Returns transaction details
 *
 * @param {Object} req - Express request object
 * @param {Object} req.body - Request body
 * @param {string} req.body.imageUrl - URL of the image to mint as NFT (required)
 * @param {string} req.body.prompt - User input text for the meme (required)
 * @param {Object} res - Express response object
 * @returns {Promise<void>}
 */
export async function mintNFT(req, res) {
  try {
    const { imageUrl, prompt } = req.body;

    // Validate required parameters
    if (!imageUrl || !prompt) {
      return res
        .status(400)
        .json({ error: "Image URL and prompt are required" });
    }

    // 1. Set up Umi instance with Irys uploader
    const rpcUrl =
      process.env.NEXT_PUBLIC_SOLANA_RPC_URL || "https://api.devnet.solana.com";
    const irysUrl =
      process.env.NEXT_PUBLIC_IRYS_URL || "https://devnet.irys.xyz";

    console.log(`Setting up Umi with RPC URL: ${rpcUrl}`);
    console.log(`Setting up Irys uploader with URL: ${irysUrl}`);

    const umi = createUmi(rpcUrl)
      .use(mplTokenMetadata())
      .use(
        irysUploader({
          address: irysUrl,
          network: "devnet",
          // Use free devnet, no need to fund
          fundAmount: 0,
        }),
      );

    // 2. Create or use existing keypair
    let keypair;
    if (process.env.SECRET_KEY) {
      // Use existing secret key from environment
      const secretKey = bs58.decode(process.env.SECRET_KEY);
      keypair = umi.eddsa.createKeypairFromSecretKey(secretKey);
    } else {
      // Generate new keypair for testing
      keypair = generateSigner(umi);
      console.log("Generated new keypair for testing:", keypair.publicKey);

      // Request small amount of SOL for testing keypair
      try {
        const signature = await umi.rpc.airdrop(keypair.publicKey, sol(0.1));
        // Wait for airdrop to confirm
        await umi.rpc.confirmTransaction(signature);
        console.log("Airdrop successful");
      } catch (airdropError) {
        console.warn(
          "Airdrop failed (might be on mainnet):",
          airdropError.message,
        );
      }
    }

    // Set the keypair as the identity and payer
    umi.use(signerIdentity(keypair));

    // 3. Create NFT metadata
    const timestamp = Math.floor(Date.now() / 1000);
    const shortPrompt =
      prompt.length > 20 ? prompt.substring(0, 20) + "..." : prompt;
    const metadata = {
      name: `Meme: ${shortPrompt}`,
      description: `Meme generated from prompt: ${prompt}`,
      image: imageUrl,
      attributes: [
        {
          trait_type: "Meme Type",
          value: "Generated",
        },
        {
          trait_type: "Timestamp",
          value: timestamp.toString(),
        },
        {
          trait_type: "Prompt",
          value: prompt,
        },
      ],
      external_url: "https://github.com/solana-labs/solana",
      seller_fee_basis_points: 500, // 5%
      creators: [
        {
          address: keypair.publicKey,
          verified: true,
          share: 100,
        },
      ],
    };

    // 4. Upload metadata to Arweave using Irys
    console.log("Uploading metadata to Arweave...");
    const metadataUri = await umi.uploader.uploadJson(metadata);
    console.log("Metadata uploaded to:", metadataUri);

    // 5. Generate mint signer
    const mint = generateSigner(umi);

    // 6. Mint NFT using mpl-token-metadata
    console.log("Minting NFT...");
    const transaction = await createNft(umi, {
      mint,
      name: `Meme: ${shortPrompt}`,
      symbol: "MEME",
      uri: metadataUri,
      sellerFeeBasisPoints: percentAmount(500), // 5%
      creators: [
        {
          address: keypair.publicKey,
          verified: true,
          share: 100,
        },
      ],
    }).sendAndConfirm(umi);

    // 7. Build Solana Explorer links
    const transactionSignature = transaction.signature;
    const mintAddress = mint.publicKey;
    const cluster = rpcUrl.includes("devnet") ? "devnet" : "mainnet";
    const transactionUrl = `https://solscan.io/tx/${transactionSignature}?cluster=${cluster}`;
    const mintUrl = `https://solscan.io/token/${mintAddress}?cluster=${cluster}`;

    console.log("NFT minted successfully!");
    console.log("Mint address:", mintAddress);
    console.log("Transaction URL:", transactionUrl);

    // 8. Return response
    res.json({
      success: true,
      mintAddress: mintAddress,
      transactionUrl: transactionUrl,
      solscanLink: mintUrl,
      transactionSignature: transactionSignature,
    });
  } catch (error) {
    console.error("Error minting NFT:", error);
    res.status(500).json({
      error: "Failed to mint NFT",
      details: error.message,
    });
  }
}
